### ISSUE TITLE
Migration error - 0 MYST balance in the app.

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/mysterium-vpn-desktop#363]
**Describe the bug**
The balance shows as 0 MYST after migration.

**To Reproduce**
Steps to reproduce the behavior | Consumer identity: 0xdcb6f3433028e02f5168c9558d74be484a7fb127

1. Checked (old) Hermes: https://hermes.mysterium.network/api/v2/data/consumer/0xdcb6f3433028e02f5168c9558d74be484a7fb127 and the channel Identity of the old Hermes is 0x59dAb984939981398170A3E1CA8C616dccF9791F.
Transaction out/sent shows here: https://polygonscan.com/address/0x59dAb984939981398170A3E1CA8C616dccF9791F#tokentxns

2. Checked (new) Hermes3: https://hermes3.mysterium.network/api/v2/data/consumer/0xdcb6f3433028e02f5168c9558d74be484a7fb127 and the channel identity of the new hermes (hermes3) is 0x8d81e092ddA3d9dF62Dd08a947739C57E15f6AA1.
Contract is just created and nothing happens and the MYST is not deposited to the new channel identity: https://polygonscan.com/address/0x8d81e092ddA3d9dF62Dd08a947739C57E15f6AA1#internaltx

**Expected behavior**
The MYST is not available in the old channel identity as it's sent out but it is expected that it should be sent to the new channel identity after migration.
 
**Screenshots**
![image](https://user-images.githubusercontent.com/68943180/175781578-4af27186-b98b-46c1-86cd-9f0bab15208b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - App Version: 10.11.1

**Additional context**
The consumer restarted the app because of my request but it didn't help and a few others face the same problem.

**Comment by adinetech** [comment]
Closing as it is fixed for the specific user.

**Comment by abdullahrafi882** [comment]
it's not solved properly my balance issue isn't resolve,, i topup again that is showing but before balance issue isn't solve and not added the balance with new balance..

**Comment by abdullahrafi882** [comment]
done, Report Id: 7631
