### ISSUE TITLE
[bug]failed to connect

### ISSUE THREAD

**Issue by Whyro** [mysteriumnetwork/mysterium-vpn-desktop#431]
failed to connect: could not start new connection, failed to start connection endpoint: could not configure device: failed to create wg interface: could not setup network: could not set dns: could not configure dns
issue happens on every single node, everytime, uninstalling did not fix the issue, i've no firewalls/antivirus installed, made a bug report on the app already

**Comment by Whyro** [comment]
putting the dns settings to system fixes the issue, but when i connect to a node i get no internet this way, putting them on any other settings gives the error above

**Comment by isaackielma** [comment]
Can you please submit your app logs so we could investigate this further with our engineering team? 

 

Access the "Help" tab section on the title bar (top of app window). Then, 'Report Bug'.

**Comment by Whyro** [comment]
done, ty

**Comment by isaackielma** [comment]
Thanks!

**Comment by isaackielma** [comment]
Could you please try installing: https://www.wintun.net/

then, move the dll file to the directory of Mysterium dVPN.

After that, restart the app (in case issue persists)> make a backup and delete the app > Reinstall app

**Comment by isaackielma** [comment]
Most likely you have already tried this, but if you haven't, please try setting DNS to automatic

<img width="1259" alt="Screenshot 2023-01-15 at 21 16 08" src="https://user-images.githubusercontent.com/84313603/212575765-446379f9-f6df-4030-886d-d3557cf55106.png">
<img width="567" alt="Screenshot 2023-01-15 at 21 16 19" src="https://user-images.githubusercontent.com/84313603/212575772-b61fb426-911c-4696-b26a-c130d47a097c.png">

**Comment by Whyro** [comment]
Setting the dns to automatic gives me the same error as cloudflare/provider
(could not dns, could not configure dns), imma try installing wintun when i
wake up ty

Il lun 16 gen 2023, 01:28 Isaackielma ***@***.***> ha scritto:

**Comment by Whyro** [comment]
> 

i tried installing wintun and putting the dll there, but the problem stays the same, i tried to reinstall as well but to no avail

**Comment by Firlej** [comment]
Got the same issue. Any updates on this so far?

**Comment by gir489returns** [comment]
I fucking hate this VPN client so much. It always has problems. Every node I try to connect to fails.

**Comment by chompomonim** [comment]
I should confirm that myst has this problem on Ubuntu Linux 23.04. But who cares about Linux users, right?
